
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://fmdvfmzdykmkmakyrtsi.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZHZmbXpkeWtta21ha3lydHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjY5OTksImV4cCI6MjA2NDc0Mjk5OX0.nawk9MmyigLOtDF7xJWO75mM9cVt8rDqLzx8PvuY_X8';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
